apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml


# you don't need to add files in here
# just simply have them in this file path:
# ubernutty-cluster/clusters/staging
# just like our apps.yaml file
#
#
