apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
#      securityContext:
#        fsGroup: 33 # www-data group ID. 
#        runAsUser: 33 # www-data group ID
#        runAsGroup: 33 # www-data group ID
  # look at docker files to documentation on the users
  # look for users/profiles to secure in the dockerfile
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 3005

#          securityContxt:        #  <------
#            allowPrivilegeEscalation: false   #  <----


          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap


#           - secretRef:
#               name: linkding-signin
# 
          volumeMounts:
            - name: audiobookshelf-data
              mountPath: /data
#            - name: audiobooks
#              mountPath: /audiobooks
#            - name: podcasts
#              mountPath: /podcasts
#            - name: config
#              mountPath: /config
#            - name: metadata
#              mountPath: /metadata
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
#        - name: audiobooks
#          hostPath:
#            path: /data/audiobookshelf/audiobooks
#            type: Directory
#        - name: podcasts
#          hostPath:
#            path: /data/audiobookshelf/podcasts
#            type: Directory
#        - name: config
#          hostPath:
#            path: /data/audiobookshelf/config
#            type: Directory
#        - name: metadata
#          hostPath:
#            path: /data/audiobookshelf/metadata
#            type: Directory
