apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: default
  labels:
    run: flabby
  name: flabby
spec:
  containers:
  - image: nginx
    name: tester
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
