apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:1IwU9K85yW+d+vTaiHcWXCoz+XjM9LEckE4VgLNB1T09o+UYTl0YjNsxkdIJaUSj3pNpLLCb5X0=,iv:LA194rwgFnilbfTdjEMQ8CMwk8WQfkjGNBae+kKN4UY=,tag:oyUsL1/Tzvpze8M3xz6zqg==,type:str]
kind: Secret
metadata:
    name: renovate-secret
sops:
    age:
        - recipient: age1ffx342fax8t80wvv93fp4srt67tdya03j9436u7qquh2cy475qds7rt755
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTkxqQkMxRnliQnk4SEdB
            a3JCS3VxNjc1WTNvRnFXRDM1Rng5UUUwNGwwClZuTnZOVEYwR0lRSm5vM3N4T3NF
            ajA2N3hVUnFjbkVtaHVqZTM5T1ArWlEKLS0tIGFnUVczbTdtUE9tdTdEdVphbHJu
            ZWtZRHBOdy9oTTFlRnlvZ0U0S0RmWTgK4f7C2OHsBlxXTEzW746JClU6OmsTqo12
            B95M9VK/PFb6z68jXnzT2Rlk6L9/ij8MerEsB386haUaazcnX9XBtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:16:03Z"
    mac: ENC[AES256_GCM,data:um3KIWFPmbfc06nC3itDCN68A+aXr5b6+DjhNJLVIwT80qinCkutQWyqJk+UGkHv7IkttEBme0nWuOZ8vZHjXVAn53P0b4AIwW05rPDbvJ4sQAkMsMaRi8npJVYpvlcxYviClGkFy363DwwoELC7Jhc0oW8afJHJTfLkLs/25JM=,iv:RC/CU/WUw6oUw2jL2BdMUK03PdlyI6VL28vP9/IyLH0=,tag:p3IYAn5GkMKcfJtRw8bD8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
